name: dex
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - chardet
  - cython
  - fasteners
  - flask
  - gunicorn
  - jinja2
  - lxml
  - matplotlib
  - msgpack-python
  - numexpr
  - pandas
  - pip
  - py-cpuinfo
  - pydantic
  - pygments
  - pytest
  - python=3.13
  - regex
  - requests
  - setuptools==80.10.2
  - ydata-profiling
  - pip:
    - clevercsv

